integrations:
  -
    name: graph-jamf
    instanceId: starbaseMalformedTest
    directory: ./.integrations/graph-jamf
    gitRemoteUrl: https://github.com/JupiterOne/graph-jamf.git
    config:
      JAMF_HOST=jamfhost
      JAMF_USERNAME=jamfusername
      JAMF_PASSWORD=redactedpassword
storage:
  engine: neo4j
  config:
    username: neo4j
    password: devpass
    uri: bolt://localhost:7687
