version: '3.8'
services:
  memgraph:
    image: 'memgraph/memgraph-platform'
    hostname: memgraph
    ports:
      - '3000:3000'
      - '7444:7444'
      - '7687:7687'
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    entrypoint: ["/usr/bin/supervisord"]
volumes:
  mg_lib:
  mg_log:
  mg_etc: