version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.3
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs
      - ./.neo4j/import:/var/lib/neo4j/import
      - ./.neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/devpass
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
